name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      # fail-fast: false
      matrix:
        # os: [ubuntu-18.04, ubuntu-latest]
        os: [ubuntu-18.04]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Display Python version
    #   run: python -c "import sys; print('Python version', sys.version)"

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        # cache path to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.os }}-${{ matrix.python-version }}-pip-
          ${{ runner.os }}-${{ matrix.os }}-${{ matrix.python-version }}-
          ${{ runner.os }}-${{ matrix.os }}-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint with Pylint - src folder
      run: |
        pylint src
    # - name: Lint with Pylint - test folder
    #   run: |
    #     pylint tests

    - name: Run test cases
      run: |
        ./run_tests.sh
